spring.application.name=yay_backend

# Don't do this in prod
spring.jwt.secret=571bbc62e69cbb6a29cc3609e44500249030808179fbc37dd88aaf9fa716a374

spring.access-token.expiration=300000
spring.refresh-token.expiration=360000000

spring.docker.compose.file=../docker-compose.yaml
spring.docker.compose.skip.in-tests=false
