services:
  postgres:
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_DB: yay
      POSTGRES_PASSWORD: postgres
    labels:
      - "org.springframework.boot.service-connection=postgres"
  frontend:
    build:
      context: ./yay_frontend
      dockerfile: Dockerfile
    ports:
      - "5173:5173"
    volumes:
      - ./yay_frontend/src:/app/src
