CREATE TABLE channels (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(35) NOT NULL,
    community_id BIGINT NOT NULL REFERENCES communities(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    UNIQUE (name, community_id)
);

CREATE TABLE channel_messages (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMPTZ DEFAULT NULL,
    deleted_at TIMESTAMPTZ DEFAULT NULL
);

CREATE TABLE channel_permissions (
    channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE CASCADE ON UPDATE RESTRICT,
    role_id BIGINT NOT NULL REFERENCES community_roles(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    can_read BOOLEAN NOT NULL DEFAULT true,
    can_write BOOLEAN NOT NULL DEFAULT true,
    PRIMARY KEY (channel_id, role_id)
);