CREATE TABLE channels (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    name VARCHAR(35) NOT NULL,
    community_id BIGINT NOT NULL REFERENCES communities(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    UNIQUE(name, community_id)
);

CREATE TABLE channel_messages (
    id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    message TEXT NOT NULL,
    user_id BIGINT NOT NULL REFERENCES users(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    channel_id BIGINT NOT NULL REFERENCES channels(id) ON DELETE RESTRICT ON UPDATE RESTRICT,
    created_at TIMESTAMPTZ NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT timezone('UTC', CURRENT_TIMESTAMP),
    deleted_at TIMESTAMPTZ DEFAULT NULL
);